config/routes.rb
Rails.application.routes.draw do
  root to: 'communities#index'

  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', as: :logout
  resources :users

  resources :communities, only: %i[index new create show] do
    resources :text_comments, only: %i[new create]
    resources :emoji_comments, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :community
  delegated_type :content, types: %w[Text Emoji]
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :comments, strict_loading: true
  validates :title, length: { minimum: 1, maximum: 40 }
end

app/models/emoji.rb
class Emoji < ApplicationRecord
  has_one :comment, as: :content, touch: true
  enum emoji_type: %i[😀 😂 😎]
  delegate :author_name, to: :comment
end

app/models/text.rb
class Text < ApplicationRecord
  has_one :comment, as: :content, touch: true
  has_rich_text :text_content
  delegate :author_name, to: :comment
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :email, uniqueness: true, presence: true

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: 'ログインしてください。'
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  def index
    @communities = Community.all
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)
    if @community.save
      redirect_to communities_path
    else
      render :new
    end
  end

  def show
    @community = Community.find(params[:id])
    @comments = @community.comments.order(created_at: :desc)
  end

  private

  def community_params
    params.require(:community).permit(:title, :owner_name)
  end
end

app/controllers/emoji_comments_controller.rb
class EmojiCommentsController < ApplicationController
  before_action :set_community
  
  def new
    @emoji = Emoji.new.build_comment
  end

  def create
    # FIXME: バリデーションエラーを無視している
    @community.comments
              .create(content: Emoji.new(emoji_type: emoji_params[:emoji_type]),
                      author_name: emoji_params[:author_name])
    redirect_to community_path(@community)
  end

  private

  def set_community
    @community = Community.find(params[:community_id])
  end

  def emoji_params
    params.require(:comment).permit(:emoji_type, :author_name)
  end
end

app/controllers/text_comments_controller.rb
class TextCommentsController < ApplicationController
  before_action :set_community
  
  def new
    @text = Text.new.build_comment
  end

  def create
    # FIXME: バリデーションエラーを無視している
    @community.comments
              .create(content: Text.new(text_content: text_params[:text_content]),
                      author_name: text_params[:author_name])
    redirect_to community_path(@community)
  end

  private

  def set_community
    @community = Community.find(params[:community_id])
  end

  def text_params
    params.require(:comment).permit(:text_content, :author_name)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to(root_path, notice: 'ログインしました。')
    else
      flash.now[:alert] = 'ログインできませんでした。'
      render :new
    end
  end

  def destroy
    logout
    redirect_to(login_path, notice: 'ログアウトしました。')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'ユーザーを新規作成しました。'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: 'ユーザー情報を変更しました。'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/new.html.haml
= link_to community_path(@community), class: 'btn btn-light mb-3' do
  %i.fas.fa-arrow-left
  戻る

.container
  %h1= t('.title', community_title: @community.title)
  = form_with model: [@community, @comment] do |form|
    = form.label :author_name, class: 'form-label'
    = form.text_field :author_name, class: 'form-control mb-2'
    = form.label :content, class: 'form-label'
    = form.rich_text_area :content, class: 'form-control mb-4'
    = form.submit '投稿', class: 'btn btn-primary'

app/views/communities/index.html.haml
.d-flex.justify-content-between.align-items-center.mb-4
  %h1= t('.title')
  = link_to new_community_path, class: 'btn btn-primary' do
    %i.fas.fa-plus
    = t('.link_to_new')

.container-fluid
  .row
    - @communities.each do |community|
      .col-md-6.col-lg-4.p-1
        .card
          .card-body
            %h4= community.title
            .small.text-muted= t('activerecord.attributes.community.owner_name') + '：' + community.owner_name
            .small.text-muted= t('activerecord.attributes.community.created_at') + '：' + l(community.created_at)
            .d-flex.justify-content-between.align-items-end.mt-2
              %div
                .small 最新のコメント投稿：
                - author_name, created_at = community.comments.order(created_at: :desc).pick(:author_name, :created_at)
                .small
                  %span= author_name
                  %span= '(' + l(created_at) + ')' if created_at.present?
              = link_to community_path(community) do
                %i.fas.fa-arrow-right
                中に入る

app/views/communities/new.html.haml
%h1= t('.title')
= form_with model: @community do |form|
  = render 'shared/error_messages', object: form.object

  = form.label :title, class: 'form-label'
  = form.text_field :title, class: 'form-control mb-2'
  = form.label :owner_name, class: 'form-label'
  = form.text_field :owner_name, class: 'form-control mb-4'
  = form.submit '作成', class: 'btn btn-primary'

app/views/communities/show.html.haml
= link_to communities_path, class: 'btn btn-light mb-3' do
  %i.fas.fa-arrow-left
  戻る

.container
  %h1= t('.title', title: @community.title)
  = link_to new_community_text_comment_path(@community), class: 'btn btn-primary' do
    %i.fas.fa-comment
    = t('.link_to_new_text_comment')
  = link_to new_community_emoji_comment_path(@community), class: 'btn btn-primary ms-1' do
    %i.fas.fa-smile
    = t('.link_to_new_emoji_comment')

  %ul.list-group.mt-4
    - @comments.each do |comment|
      %li.list-group-item
        .fs-5= comment.author_name
        .fs-6.mb-3= l(comment.created_at, format: :long)
        - if comment.text?
          .fs-6= comment.text.text_content
        - else
          .fs-1= comment.emoji.emoji_type

app/views/emoji_comments/new.html.haml
= link_to community_path(@community), class: 'btn btn-light mb-3' do
  %i.fas.fa-arrow-left
  戻る

.container
  %h1= t('.title', community_title: @community.title)
  = form_with model: @emoji, url: community_emoji_comments_path do |form|
    = form.label :author_name, class: 'form-label'
    = form.text_field :author_name, class: 'form-control mb-2'
    = form.label :emoji_type, class: 'form-label'
    = form.select :emoji_type, Emoji.emoji_types.keys.to_a, {}, class: 'form-control mb-4'
    = form.submit '投稿', class: 'btn btn-primary'

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container-fluid
    = link_to root_path, class: 'navbar-brand' do
      Rails6.1掲示板
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          = link_to root_path, class: 'nav-link' do
            トップ
        %li.nav-item
          = link_to new_community_path, class: 'nav-link' do
            コミュニティを作る
      .d-flex
        -if current_user
          .nav-item.dropdown
            %a.nav-link.text-white.dropdown-toggle#navbarDropdownMenuLink{href: "#", role: "button", "data-bs-toggle": "dropdown", "aria-expanded": "false"}
              = current_user.email
            %ul.dropdown-menu{"aria-labelledby": "navbarDropdownMenuLink"}
              %li
                = link_to t('header.to_user_edit'), edit_user_path(current_user.id), class: 'dropdown-item'
              %li
                = link_to t('header.to_logout'), :logout, method: :post, class: 'dropdown-item'
        - else
          = link_to t('header.to_register'), new_user_path, class: 'btn btn-primary me-2'
          = link_to t('header.to_login'), :login, class: 'btn btn-secondary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rails61HandsOn
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render '/layouts/header'
    - if flash[:notice]
      .alert.alert-info.m-2= flash[:notice]
    - if flash[:alert]
      .alert.alert-warning.m-2= flash[:alert]
    .container-fluid.pt-4.px-4
      = yield

app/views/shared/_error_messages.html.haml
- if object.errors.present?
  .card.mb-2.border-danger
    .card-header.bg-danger.text-white
      エラーがあります
    .card-body
      %ul
        - object.errors.each do |e|
          %li= e.full_message

app/views/text_comments/new.html.haml
= link_to community_path(@community), class: 'btn btn-light mb-3' do
  %i.fas.fa-arrow-left
  戻る

.container
  %h1= t('.title', community_title: @community.title)
  = form_with model: @text, url: community_text_comments_path do |form|
    = form.label :author_name, class: 'form-label'
    = form.text_field :author_name, class: 'form-control mb-2'
    = form.label :text_content, class: 'form-label'
    = form.rich_text_area :text_content, class: 'form-control mb-4'
    = form.submit '投稿', class: 'btn btn-primary'

app/views/user_sessions/new.html.haml
%h1= t '.title'
= form_with url: login_path, method: :post do |f|
  = f.label t('.email'), class: 'form-label'
  = f.text_field :email, class: 'form-control mb-2'

  = f.label t('.password'), class: 'form-label'
  = f.password_field :password, class: 'form-control mb-4'

  = f.submit t('.submit'), class: 'btn btn-primary'

app/views/users/_form.html.haml
= form.label :password, class: 'form-label'
= form.password_field :password, class: 'form-control mb-2'

= form.label :password_confirmation, class: 'form-label'
= form.password_field :password_confirmation, class: 'form-control mb-2'

app/views/users/edit.html.haml
%h1= t '.title'

= form_with model: @user do |f|
  = render 'shared/error_messages', object: f.object
  = render 'form', form: f
  = f.submit t('.submit'), class: 'btn btn-primary'

app/views/users/new.html.haml
%h1= t '.title'

= form_with model: @user do |f|
  = render 'shared/error_messages', object: f.object
  
  = f.label :email, class: 'form-label'
  = f.text_field :email, class: 'form-control mb-2'

  = render 'form', form: f
  = f.submit t('.submit'), class: 'btn btn-primary'